### ISSUE TITLE
Bitbucket Pipeline: Error: EACCES: permission denied, mkdir '/root/.npm/sentry-cli'

### ISSUE THREAD

**Issue by sebestenyb** [expo/sentry-expo#47]
Hi,

I'm trying to setup a CI build for an expo project, which includes the   ` "sentry-expo": "^1.11.2"` package.

The build fails in Bitbucket Pipeline with the following error:

```
> @sentry/cli@1.37.4 install /opt/atlassian/pipelines/agent/build/node_modules/@sentry/cli
> node scripts/install.js
Error: EACCES: permission denied, mkdir '/root/.npm/sentry-cli'
```

The pipeline files is 

```
image: node:alpine
definitions:
  caches:
    npm: ~/.npm
    jest: .jest
pipelines:
  default:
    - step:
        name: Test with Jest
        caches:
          - npm
          - jest
        script:
          - apk add --no-cache git
          - npm ci
          - npx jest --ci
    - step:
        name: Deploy to Expo
        deployment: test
        caches:
          - npm
        script:
          - apk add --no-cache bash git
          - npm install -g expo-cli
          - npm ci
          - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          - npx expo publish --non-interactive
```

The build script runs as root.
Not sure this is the proper project to raise this issue, as the error is coming through `expo/sentry-expo => getsentry/react-native-sentry => getsentry/sentry-wizard => getsentry/cli`

Any help is appreciated, 

Cheers, Sebi
